[build]
  publish = "src"  # O la carpeta donde se encuentran tus archivos estáticos
  functions = "netlify/functions"

[[redirects]]
  from = "/register"
  to = "/.netlify/functions/register"
  status = 200
  force = true
